spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

server:
  port: 5005
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
    gateway:
      enabled: true