spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    preferIpAddress: false
    appname: registryCheck
    app-group-name: sys
