spring:
  application:
    name: trace-service
server:
  port: 5006
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: false
management:
  endpoints:
    web:
      exposure:
        include: '*'